"project_id": "517998"                     #open project and go to Tools > API 
"api_token": "97d67c56c1f0801699c798cf077a5cbe3c19bd1132f4aa8a623f284c92acbf4d07c7f3696d0466a3"          #open profile settings and go to API > New Token > create Token
"base_path": "/demowithgithub"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/de_locale/locale_en.properties",                                       #source files filter
    "translation": "/locale/en/folder1/locale_en"        #where translations are stored
  },
  {
    "source": "/de_locale/locale_de.properties",                                       #source files filter
    "translation": "/locale/de/folder1/locale_de"        #where translations are stored
  }
]
